import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk, Libre_Franklin, Plus_Jakarta_Sans,Inter_Tight } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const plusJakartaSans = Plus_Jakarta_Sans({
//   variable: "--font-plus-jakarta",
//   subsets: ["latin"],
// });
// const libreFranklin = Libre_Franklin({
//   variable: "--font-plus-jakarta",
//   subsets: ["latin"],
// });
const interTight = Inter_Tight({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
});

const spaceGrosteck = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Peace David - React JS Developer | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${interTight.variable} ${geistMono.variable} ${spaceGrosteck.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
